# Generated by Django 4.0.3 on 2022-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_newuser_first_name_alter_newuser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
