# Generated by Django 4.0.3 on 2022-04-05 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_newuser_first_name_alter_newuser_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=80, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
