# Generated by Django 4.0.3 on 2022-04-05 20:08

from django.db import migrations, models
import validators.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_newuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile/', validators=[validators.image_validator.MaxFileSizeInMbValidator(2)]),
        ),
    ]
