# Generated by Django 4.0.3 on 2022-03-19 15:03

import django.core.validators
from django.db import migrations, models
import validators.image_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('train', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gymnasts/', validators=[validators.image_validator.MaxFileSizeInMbValidator(5)])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotesConjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotesIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('train', models.CharField(max_length=150)),
                ('birthdate', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trainers/', validators=[validators.image_validator.MaxFileSizeInMbValidator(5)])),
                ('description', models.TextField()),
            ],
        ),
    ]
