# Generated by Django 4.0.3 on 2022-04-13 14:05

import cloudinary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_club_organisation', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('competition_name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('competition_place', models.CharField(max_length=60)),
                ('competition_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('Pre-benjamín', 'Pre-benjamín'), ('Benjamín', 'Benjamín'), ('Alevín', 'Alevín'), ('Infantil', 'Infantil'), ('Cadete', 'Cadete')], max_length=30)),
                ('train', models.CharField(choices=[('Individual', 'Individual'), ('Conjunto', 'Conjunto'), ('Individual y Conjunto', 'Individual y Conjunto')], max_length=150)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2)])),
                ('train', models.CharField(choices=[('Individual', 'Individual'), ('Conjunto', 'Conjunto'), ('Individual y Conjunto', 'Individual y Conjunto')], max_length=150)),
                ('birthdate', models.DateField()),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NotesTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_competition', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('competition_place_on_board', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.competition')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.team')),
            ],
        ),
        migrations.CreateModel(
            name='NotesIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_competition', models.DecimalField(decimal_places=3, max_digits=5, validators=[django.core.validators.MinValueValidator(0.001)])),
                ('competition_place_on_board', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.competition')),
                ('gymnast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.gymnast')),
            ],
        ),
        migrations.AddField(
            model_name='gymnast',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.team'),
        ),
    ]
