# Generated by Django 4.0.3 on 2022-03-08 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Gymnast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('last_name', models.CharField(max_length=20, validators=[django.core.validators.MinValueValidator(2)])),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('photo', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
