# Generated by Django 4.0.3 on 2022-03-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesindividual',
            old_name='competition_id',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='notesindividual',
            old_name='gymnast_id',
            new_name='gymnast',
        ),
        migrations.RenameField(
            model_name='notesteam',
            old_name='competition_id',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='notesteam',
            old_name='team_id',
            new_name='team',
        ),
    ]
