# Generated by Django 4.0.3 on 2022-03-19 15:11

from django.db import migrations, models
import validators.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gymnasts/', validators=[validators.image_validator.MaxFileSizeInMbValidator(1)]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', validators=[validators.image_validator.MaxFileSizeInMbValidator(1)]),
        ),
    ]
