# Generated by Django 4.0.3 on 2022-03-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
