# Generated by Django 4.0.3 on 2022-03-22 10:39

from django.db import migrations, models
import validators.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_gymnast_category_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='gymnasts/', validators=[validators.image_validator.MaxFileSizeInMbValidator(2)]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/'),
        ),
    ]
