# Generated by Django 4.0.3 on 2022-03-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_gymnast_photo_alter_trainer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnast',
            name='category',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
