# Generated by Django 4.0.3 on 2022-03-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_rename_competition_id_notesindividual_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='category',
            field=models.CharField(choices=[('Pre-benjamín', 'Pre-benjamín'), ('Benjamín', 'Benjamín'), ('Alevín', 'Alevín'), ('Infantil', 'Infantil'), ('Cadete', 'Cadete')], max_length=30),
        ),
    ]
