# Generated by Django 4.0.3 on 2022-03-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesindividual',
            name='competition',
        ),
        migrations.AddField(
            model_name='notesindividual',
            name='competition',
            field=models.ManyToManyField(to='club.competition'),
        ),
    ]
