# Generated by Django 4.0.3 on 2022-03-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_gymnast_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gymnast',
            name='train',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
