# Generated by Django 4.0.3 on 2022-04-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_contact_email_alter_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesindividual',
            name='nota_competition',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='notesteam',
            name='nota_competition',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
