# Generated by Django 4.0.3 on 2022-03-22 10:48

from django.db import migrations, models
import validators.image_validator


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_gymnast_photo_alter_trainer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='trainers/', validators=[validators.image_validator.MaxFileSizeInMbValidator(2)]),
        ),
    ]
