# Generated by Django 4.0.3 on 2022-04-04 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_competition_competition_club_organisation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesindividual',
            name='competition_place_on_board',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='notesteam',
            name='competition_place_on_board',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
