# Generated by Django 4.0.3 on 2022-03-25 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_remove_notesindividual_competition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='trainers',
        ),
    ]
