# Generated by Django 4.0.3 on 2022-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_alter_notesindividual_competition_place_on_board_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesindividual',
            name='competition_place_on_board',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notesteam',
            name='competition_place_on_board',
            field=models.IntegerField(),
        ),
    ]
