# Generated by Django 4.0.3 on 2022-03-25 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_gymnast_team_alter_team_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnast',
            name='team',
        ),
    ]
