# Generated by Django 4.0.3 on 2022-03-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_remove_gymnast_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='category',
        ),
        migrations.AddField(
            model_name='gymnast',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(choices=[('Pre-benjamín', 'Pre-benjamín'), ('Benjamín', 'Benjamín'), ('Alevín', 'Alevín'), ('Infantil', 'Infantil'), ('Cadete', 'Cadete')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
