# Generated by Django 4.0.3 on 2022-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_team_description_team_photo_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymnast',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
