# Generated by Django 4.0.3 on 2022-03-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_gymnast_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='train',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Conjunto', 'Conjunto'), ('Individual y Conjunto', 'Individual y Conjunto')], default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='train',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Conjunto', 'Conjunto'), ('Individual y Conjunto', 'Individual y Conjunto')], max_length=150),
        ),
    ]
