# Generated by Django 4.0.3 on 2022-03-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_alter_gymnast_train_alter_trainer_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gymnast',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
