# Generated by Django 4.0.3 on 2022-03-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_alter_gymnast_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gymnast',
            name='slug',
        ),
    ]
